spring.application.name=tjphoto

spring.datasource.url=jdbc:mariadb://localhost:3306/photos
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# # 매퍼 위치
mybatis.mapper-locations=classpath:/mappers/**/*.xml
# 매퍼가 매핑하기 위한 객체의 패키지 주소
mybatis.type-aliases-package=com.example.tjphoto.vo
# 자바의 카멜표기법과 데이터베이스 컬럼의 스네이크 표기법의 컬럼을 자동으로 매핑
mybatis.configuration.map-underscore-to-camel-case=true
# logging 이거는 로그를 남겨라 라는 의미
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

file.upload-path=C:/upload/